source 'http://rubygems.org'

ruby "1.9.3"

gem 'rack'
gem 'webrick'
gem 'radius'
gem 'pry'
gem 'pry-stack_explorer'
gem 'chronic'
gem 'htmlentities'
gem 'nokogiri', '= 1.6.7.2'
gem 'sanitize'
gem 'colorize'
gem 'activesupport'
gem 'actionview'
gem 'faker','~>1.6.5'
gem 'git'
gem 'wannabe_bool'
gem 'httparty'
gem 'dentaku'
