source 'http://rubygems.org'

gem 'rack'
gem 'webrick'
gem 'radius'
gem 'pry'
gem 'pry-stack_explorer'
gem 'chronic'
gem 'htmlentities'
gem 'nokogiri'
gem 'sanitize'
gem 'colorize'
gem 'activesupport'
gem 'actionview'
gem 'faker', '1.8.7'
gem 'git'
gem 'wannabe_bool'
gem 'httparty'
gem 'dentaku'
gem 'tilt'
gem 'github_changelog_generator'
